#!/bin/sh

set -e

case "$1" in
  configure)
     adduser --quiet \
             --system \
             --group \
             --home "/var/lib/hubic" \
             hubic
     chown hubic:hubic /etc/hubic/password /etc/hubic/exclusions
     
     # add to default runlevel
     sudo update-rc.d hubic defaults
  ;;
esac

exit 0;
